from enum import IntEnum

CURRENT_VERSION = 8
USERNAME_PASSWORD_LENGTH = 32
SYMBOL_LENGTH = 64
EXCHANGE_LENGTH = 16
TEXT_DESCRIPTION_LENGTH = 96
TEXT_MESSAGE_LENGTH = 256


class MessageType(IntEnum):
    LOGON_REQUEST = 1
    LOGON_RESPONSE = 2
    HEARTBEAT = 3
    LOGOFF = 5
    ENCODING_REQUEST = 6
    ENCODING_RESPONSE = 7

    MARKET_DATA_REQUEST = 101
    MARKET_DATA_REJECT = 103
    MARKET_DATA_SNAPSHOT = 104
    MARKET_DATA_UPDATE_TRADE = 107
    MARKET_DATA_UPDATE_BID_ASK = 108
    MARKET_DATA_FEED_STATUS = 100

    SUBMIT_NEW_SINGLE_ORDER = 208
    CANCEL_ORDER = 203
    ORDER_UPDATE = 301
    OPEN_ORDERS_REQUEST = 300

    HISTORICAL_PRICE_DATA_REQUEST = 800
    HISTORICAL_PRICE_DATA_RESPONSE_HEADER = 801
    HISTORICAL_PRICE_DATA_RECORD_RESPONSE = 803
    HISTORICAL_PRICE_DATA_TICK_RECORD_RESPONSE = 804
    HISTORICAL_PRICE_DATA_RESPONSE_TRAILER = 807


class EncodingEnum(IntEnum):
    BINARY_ENCODING = 0
    BINARY_WITH_VARIABLE_LENGTH_STRINGS = 1
    JSON_ENCODING = 2
    JSON_COMPACT_ENCODING = 3
    PROTOCOL_BUFFERS = 4


class LogonStatusEnum(IntEnum):
    LOGON_SUCCESS = 1
    LOGON_ERROR = 2
    LOGON_ERROR_NO_RECONNECT = 3
    LOGON_RECONNECT_NEW_ADDRESS = 4


class RequestActionEnum(IntEnum):
    SUBSCRIBE = 1
    UNSUBSCRIBE = 2
    SNAPSHOT = 3


class OrderTypeEnum(IntEnum):
    ORDER_TYPE_UNSET = 0
    ORDER_TYPE_MARKET = 1
    ORDER_TYPE_LIMIT = 2
    ORDER_TYPE_STOP = 3
    ORDER_TYPE_STOP_LIMIT = 4


class BuySellEnum(IntEnum):
    BUY_SELL_UNSET = 0
    BUY = 1
    SELL = 2


class TimeInForceEnum(IntEnum):
    TIF_UNSET = 0
    TIF_DAY = 1
    TIF_GOOD_TILL_CANCELED = 2
    TIF_GOOD_TILL_DATE_TIME = 3
    TIF_IMMEDIATE_OR_CANCEL = 4
